window:
  padding:
    x: 20
    y: 20

  decorations: full
  startup_mode: maximized

colors:
  # Default colors
  primary:
    background: '0x161616'
    foreground: '0xc7c7c7'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'
  # Normal colors
  normal:
    black:   '0x161616'
    red:     '0xfd4285'
    green:   '0xa6e22d'
    yellow:  '0xe5da72'
    blue:    '0x0094d8'
    magenta: '0x9a37ff'
    cyan:    '0x50b6d8'
    white:   '0xc7c7c7'
  # Bright colors
  bright:
    black:   '0x676767'
    red:     '0xfa7fac'
    green:   '0xbde271'
    yellow:  '0xfff27f'
    blue:    '0x00bdff'
    magenta: '0xbd9eff'
    cyan:    '0x5ed6fe'
    white:   '0xfeffff'
